"""initial migration

Revision ID: b653fdcd8a70
Revises: fa5c31411c0a
Create Date: 2026-07-19 10:15:04.879005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b653fdcd8a70'
down_revision: Union[str, Sequence[str], None] = 'fa5c31411c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'created_at')
    # ### end Alembic commands ###
